server:
  port: 8081
  servlet:
    context-path: /events
  error:
    include-binding-errors: always
    include-message: always

environment: "local"

logging:
  level:
    org.springframework:
      security: info
    web: info